### ISSUE TITLE
Can't  compile the addon properly

### ISSUE THREAD

**Issue by zain-creation** [danielsen/node-pmta#5]
Hi nielson, Thnks for this great work, i have some compilation issus when i want to compile the addon can you tell me the version of pmta that depend this addon and others ...
 thank you :+1:

**Comment by danielsen** [comment]
This is tested with PMTA API 4.x and up, Node 4.x. Can you provide specifics on the error, the PMTA version, and the NodeJS version that you're using?

**Comment by zain-creation** [comment]
Hi nielson,
Here the error 
../node_modules/nan/nan_callbacks_12_inl.h:480: warning: ‘void Nan::imp::IndexDeleterCallbackWrapper(uint32_t, const v8::PropertyCallbackInfo<v8::Boolean>&)’ defined but not used
../node_modules/nan/nan_callbacks_12_inl.h:496: warning: ‘void Nan::imp::IndexQueryCallbackWrapper(uint32_t, const v8::PropertyCallbackInfo<v8::Integer>&)’ defined but not used
make: *** [Release/obj.target/pmta/src/pmta.o] Error 1
make: Leaving directory `/root/pmta-node/node-pmta/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 2.6.32-642.11.1.el6.x86_64
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "build"
gyp ERR! cwd /root/pmta-node/node-pmta
gyp ERR! node -v v6.9.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 


thnks :)

**Comment by zain-creation** [comment]
Here the Environment 
Linux Centos 6.9, Kernel version : Linux 2.6.32-642.11.1.el6.x86_64
Node version : v6.9.2
node-gyp version : v3.4.0
PMTA version :  3.5


thanks for all effort that you doing man.

**Comment by danielsen** [comment]
Thanks for the information. At first glance I would say this is probably a conflict between NAN and NodeJs. Possibly the NAN version used in building the code is not compatible with Node v6+. 

As an short-term solution you might want to give Node 4 a try. 

I'll get a CentOS 6.9 VM up in the next day or two so I see more closely what's going on and get a fix in place.

**Comment by zain-creation** [comment]
Hi Dan,
i switch to version 0.10 and its compiled seccusfully :)

can i have your email

**Comment by danielsen** [comment]
Closing. Build resolved to 6.10.x
