### ISSUE TITLE
issus merge sender with from

### ISSUE THREAD

**Issue by zain-creation** [danielsen/node-pmta#6]
Hi guys, 
I have one issus with node-pmta plugin, it merge the sender with From header in Return-Path can someone help me to fix that.

**Comment by danielsen** [comment]
Can you provide a list of the headers you're passing in along with the final output of the message?

**Comment by zain-creation** [comment]
Hi Dan, thanks for reply on me,
This is the list of header that i put 
/********* CODE ********/
var sender    = "bounces@example.com";


var recipients = [
  {
    "to"    : "fayssal.tahtoub@gmail.com",
    "fname" : "fayssal tahtoub"
  }
];

var payload = [
  "From: [*from]",
  "To: <[*to]>",
  "Subject: PMTA TEST MESSAGE",
  "MIME-Version: 1.0",
  "Content-Type: text/plain; charset=utf-8",
  "Content-Transfer-Encoding: 7bit",
  "\n",
  "Hi this is fisrt example with node-pmta, [fname]\n"
].join("\n");

/********** END CODE **********/

Return-Path Header from gmail ISP:
Return-Path: <bounces-fayssal.tahtoub=gmail.com@example.com> 

it merge the sender with to and put it in Return-Path as you see
thnks.

**Comment by danielsen** [comment]
It looks like you're calling the `setVerp(true)` method which instructs PMTA to use VERP when constructing the final message. More on VERP: https://en.wikipedia.org/wiki/Variable_envelope_return_path. You can either omit the call to `setVerp()` or call `setVerp(false)` to turn off VERP. If you turn VERP off, the Return-Path field will match the sender or whatever you pass in as a Return-Path field via the payload.

**Comment by danielsen** [comment]
Closing. Please re-open if needed.
