### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by nebaz** [danielsen/node-pmta#8]
fatal error: submitter/Message.hxx: No such file or directory

**Comment by danielsen** [comment]
That error indicates that the PMTA API headers can't be found. Typically, these are in `opt/pmta/api/include`. 

If they're not there, try re-installing the PMTA API. If they're installed in a different directory you need to edit the include directory in the binding.gyp file. Replace the entry in the `include_dirs` array in binding.gyp with the correct location of the files and rebuild.

**Comment by nebaz** [comment]
OK. But I do not have pmta in my server. There is pmta in other server.
